name: Sync to Gitlab

on:
  push:
    branches:
      - main

jobs:
  trigger_pipeline:
    name: Trigger GitLab pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Run pipeline
        run: curl -X POST --fail -F token=${{ secrets.GITLAB_TOKEN }} -F ref=github ${{ secrets.GITLAB_URL }}